-- MySQL Script generated by MySQL Workbench
-- Wed May  7 21:44:04 2025
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Client` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Client` (
  `id_client` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `Clientcol` VARCHAR(255) NOT NULL,
  `adresse` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`id_client`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Personnel`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Personnel` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Personnel` (
  `id_personnel` INT NOT NULL,
  `nom` VARCHAR(255) NOT NULL,
  `role` VARCHAR(255) NOT NULL,
  `salaire` FLOAT NOT NULL,
  PRIMARY KEY (`id_personnel`),
  UNIQUE INDEX `idPersonnel_UNIQUE` (`id_personnel` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Reservation`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Reservation` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Reservation` (
  `id_reservation` INT NOT NULL,
  `date_reservation` DATETIME NOT NULL,
  `num_table` INT NOT NULL,
  `nombre_pers` INT NOT NULL,
  `id_client` INT NOT NULL,
  PRIMARY KEY (`id_reservation`),
  UNIQUE INDEX `idReservation_UNIQUE` (`id_reservation` ASC) VISIBLE,
  INDEX ` _idx` (`id_client` ASC) VISIBLE,
  CONSTRAINT ` `
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Commande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Commande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Commande` (
  `id_commande` INT NOT NULL,
  `date_commande` DATETIME NOT NULL,
  `id_client` INT NOT NULL,
  `id_personnel` INT NOT NULL,
  `cout_total` FLOAT NOT NULL,
  PRIMARY KEY (`id_commande`),
  UNIQUE INDEX `id_commande_UNIQUE` (`id_commande` ASC) VISIBLE,
  INDEX `idclient_idx` (`id_client` ASC) VISIBLE,
  INDEX `idpersonnel_idx` (`id_personnel` ASC) VISIBLE,
  CONSTRAINT `idclient`
    FOREIGN KEY (`id_client`)
    REFERENCES `mydb`.`Client` (`id_client`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idpersonnel`
    FOREIGN KEY (`id_personnel`)
    REFERENCES `mydb`.`Personnel` (`id_personnel`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Menu`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Menu` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Menu` (
  `id_menu` INT NOT NULL,
  `nom_plat` VARCHAR(255) NOT NULL,
  `description` VARCHAR(255) NOT NULL,
  `prix` FLOAT NOT NULL,
  `type` VARCHAR(45) NOT NULL DEFAULT 'entree,dessert,resistance',
  PRIMARY KEY (`id_menu`),
  UNIQUE INDEX `id_menu_UNIQUE` (`id_menu` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`DetailCommande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`DetailCommande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`DetailCommande` (
  `id_commande` INT NOT NULL,
  `id_menu` INT NOT NULL,
  `qte_commande` INT NOT NULL,
  `prix_unit` VARCHAR(45) NULL,
  PRIMARY KEY (`id_commande`, `id_menu`),
  UNIQUE INDEX `id_commande_UNIQUE` (`id_commande` ASC) VISIBLE,
  INDEX `idmenu_idx` (`id_menu` ASC) VISIBLE,
  CONSTRAINT `idcommande`
    FOREIGN KEY (`id_commande`)
    REFERENCES `mydb`.`Commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `idmenu`
    FOREIGN KEY (`id_menu`)
    REFERENCES `mydb`.`Menu` (`id_menu`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`EtatCommande`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`EtatCommande` ;

CREATE TABLE IF NOT EXISTS `mydb`.`EtatCommande` (
  `id_livraison` INT NOT NULL,
  `id_commande` INT NOT NULL,
  `date_livraison` DATETIME NOT NULL,
  `etat_commande` VARCHAR(45) NOT NULL DEFAULT 'encours,livre,annule',
  PRIMARY KEY (`id_livraison`),
  INDEX `commandeid_idx` (`id_commande` ASC) VISIBLE,
  CONSTRAINT `commandeid`
    FOREIGN KEY (`id_commande`)
    REFERENCES `mydb`.`Commande` (`id_commande`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
